FROM node:lts-slim@sha256:c097018182469e8391a577955ef25f0d2ac9b0b19179835d621df48c978fa24d AS build
WORKDIR /app
COPY package*.json /app
RUN npm ci --only=production


FROM node:lts-slim@sha256:c097018182469e8391a577955ef25f0d2ac9b0b19179835d621df48c978fa24d
ENV REACT_APP_BASE_URL=http://localhost:5000
ENV NODE_ENV production
USER node
WORKDIR /app
COPY --chown=node:node --from=build /app/node_modules /app/node_modules
COPY --chown=node:node . /app
EXPOSE 3000
CMD npm run build
