FROM node:lts-slim@sha256:41bbb713cb3ac5f7d531ccdc156d2611f019b50b9c478d6475c79ced618640f0 AS build
WORKDIR /app
COPY package*.json /app
RUN npm ci --only=production


FROM node:lts-slim@sha256:41bbb713cb3ac5f7d531ccdc156d2611f019b50b9c478d6475c79ced618640f0
ENV REACT_APP_BASE_URL=http://localhost:5000
ENV NODE_ENV production
USER node
WORKDIR /app
COPY --chown=node:node --from=build /app/node_modules /app/node_modules
COPY --chown=node:node . /app
EXPOSE 3000
CMD npm run build
