##############################################################################################################
# Title: Github Actions workflow for merged/closed PRs                                                       #
# Author: Brenner, M.                                                                                        #
# Date: 2020                                                                                                 #                                                                                    #
# Availability: https://brennerm.github.io/posts/trigger-github-actions-on-pr-close.html                     #
##############################################################################################################


name: Publish Docker image

on:
  pull_request:
    types: [ "closed" ]

env:
  REGISTRY: valledeimulini

jobs:
  push_to_registry:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.event.repository.name }}:ci-${GITHUB_SHA::7}
